# .github/workflows/ci.yml

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout your repository
      - uses: actions/checkout@v3

      # 2) Install Java 17 and sbt
      - name: Setup Java & sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "17"
          sbt-version: "1.9.0"

      # 3) Cache sbt artifacts for faster builds
      - name: Cache sbt directories
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      # 4) Run compilation, tests and coverage
      - name: Run sbt clean, tests & coverage
        run: sbt clean coverage test

      # 5) Publish coverage report to Coveralls
      - name: Publish coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: target/scala-2.13/scoverage-report/scoverage.lcov
