name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache sbt
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Run sbt tests
        run: sbt clean coverage test
      - name: Publish coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ COVERALLS_REPO_TOKEN=fG2nomRUSXzQwYWGnsbSH9I1fh619yJu3}}
          path-to-lcov: target/scala-2.13/scoverage-report/scoverage.lcov
